name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: [docs/website/**]

jobs:
  build:
    # prerequisites...
    - name: Install Prince
      run: |
        curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
        tar zxf prince-14.2-linux-generic-x86_64.tar.gz
        cd prince-14.2-linux-generic-x86_64
        yes "" | sudo ./install.sh

    - name: Build PDF
      run: npx docusaurus-prince-pdf -u https://forjagames.github.io/fg-api/docs

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: result
        # The output filename can be specified with --output option
        path: pdf/nexus-docs.pdf
        if-no-files-found: error
